### ISSUE TITLE
Missing eigen repo

### ISSUE THREAD

**Issue by jimnarey** [HipsterSloth/PSVRTracker#2]
I tried to clone the PSVRTracker repo, including submodules, but it failed at the 'eigen' repo. If you attempt to access it through the Github website it results in a 404.

**Comment by HipsterSloth** [comment]
oh sorry about that. I noticed that that previous repo I was using went away. I'll fix that submodule dependency up tonight.

**Comment by HipsterSloth** [comment]
Fixed in 9d8b840671bc2c5a0dd7402ddde2cd0ea91af7de.

Just to set expectations once you get this built, I should mention that this project is still very much in development. While I have implemented support for multiple camera types I still haven't gotten multi-camera tracking working yet. That is next up after I get psmove controller tracking ported over. Also I still need to improve the camera profiles. The current set of camera intrinsics I have so far are not great.
